# Generated by Django 4.2.9 on 2026-03-03 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='research_groups/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('founder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='research_groups', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Araştırma Grubu',
                'verbose_name_plural': 'Araştırma Grupları',
                'db_table': 'research_groups',
            },
        ),
    ]
