# Generated by Django 4.2.9 on 2026-03-03 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(blank=True, max_length=500)),
                ('thesis_type', models.CharField(choices=[('masters', 'Yüksek Lisans'), ('phd', 'Doktora')], max_length=10)),
                ('year', models.IntegerField()),
                ('abstract', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='theses/pdfs/')),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_theses', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_theses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tez',
                'verbose_name_plural': 'Tezler',
                'db_table': 'theses',
                'ordering': ['-year'],
            },
        ),
    ]
