# Generated by Django 4.2.9 on 2026-03-03 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(blank=True, max_length=500)),
                ('pub_type', models.CharField(choices=[('article', 'Makale'), ('book', 'Kitap'), ('book_chapter', 'Kitap Bölümü'), ('conference', 'Bildiri'), ('other', 'Diğer')], max_length=20)),
                ('year', models.IntegerField()),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/pdfs/')),
                ('authors', models.ManyToManyField(blank=True, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yayın',
                'verbose_name_plural': 'Yayınlar',
                'db_table': 'publications',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
